-- MySQL Script generated by MySQL Workbench
-- Sat Jan 12 15:25:10 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_up2date
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_up2date
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_up2date` DEFAULT CHARACTER SET utf8 ;
USE `db_up2date` ;

-- -----------------------------------------------------
-- Table `db_up2date`.`tbl_assignments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_up2date`.`tbl_assignments` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `subject_id` INT(11) UNSIGNED NOT NULL,
  `name` VARCHAR(250) NOT NULL,
  `due_date` INT(11) NOT NULL,
  `description` VARCHAR(2000) NULL DEFAULT NULL,
  `points` INT(3) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tbl_assignments_tbl_subjects1_idx` (`subject_id` ASC),
  CONSTRAINT `fk_tbl_assignments_tbl_subjects1`
    FOREIGN KEY (`subject_id`)
    REFERENCES `db_up2date`.`tbl_subjects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
